### ISSUE TITLE
Format time display on x Axis

### ISSUE THREAD

**Issue by nichliu** [esnet/react-timeseries-charts#148] opened 2017-04-25 16:46 UTC
I would like to use 24 hours to format x Axis time display instead of 12 hours style, How can I do it?

**Comment by pjm17971** [comment] 2017-04-25 17:22
I believe this isn't currently possible. It would be a fairly straightforward change to add a conditional here:
https://github.com/esnet/react-timeseries-charts/blob/master/src/components/TimeAxis.js#L74
i.e. if the format passed in here is a string, and not one of the strings listed, then use that with d3 format.
And then submit a PR.

I can do it in time, but it's unlikely for a few weeks.

**Comment by pjm17971** [comment] 2017-04-25 17:25
Actually, this is a duplicate of https://github.com/esnet/react-timeseries-charts/issues/86
I'm closing this in favor of that one. But feel free to take a stab at it.

**Closed by pjm17971** 2017-04-25 17:25 UTC
Labels: enhancement
