### ISSUE TITLE
Website for documentation doesn't load in Safari

### ISSUE THREAD

**Issue by robphilipp** [esnet/react-timeseries-charts#201] opened 2017-12-05 13:33 UTC
http://software.es.net/react-timeseries-charts

Seems to point to an empty page. Used to have documentation for usage and API.

**Comment by pjm17971** [comment] 2017-12-05 13:36
It seems ok to me. What browser etc are you using?

**Comment by robphilipp** [comment] 2017-12-05 13:39
LOL. Sorry. It doesn’t seem to load on Safari, but on Chrome and Firefox and it works perfectly. Not sure if this is an issue on my end, or Safari.

Thanks for the quick response.

Rob

**Comment by pjm17971** [comment] 2017-12-05 14:47
<img width="1324" alt="screen shot 2017-12-05 at 6 21 33 am" src="https://user-images.githubusercontent.com/1288813/33612955-17c2a288-d988-11e7-817c-1e7db4866b6b.png">

**Comment by pjm17971** [comment] 2017-12-21 17:58
I added [help wanted] to this, because I really don't know why this doesn't work. Anyone have an idea?

**Comment by sartaj10** [comment] 2018-05-22 16:17
Should be fixed in the upcoming release (v0.15.x)

**Comment by robphilipp** [comment] 2018-05-22 17:28
Cool. Thanks. BTW I find react-timeseries-charts really awesome!

**Comment by sartaj10** [comment] 2018-05-22 17:29
Thanks a lot! 👍

**Comment by pjm17971** [comment] 2018-08-19 20:33
@xapple The help wanted tag still applies to this item.

**Comment by iabw** [comment] 2018-09-19 01:10
I think this is just what Sartaj meant before, but -

A local built version run with [serve](https://www.npmjs.com/package/serve) works fine. It's only in the production website that the problem is visible.

The [main.js](http://software.es.net/react-timeseries-charts/static/js/main.ee096215.js) on the production site isn't minified, but the main.js produced when running `npm run build-website` is. So some part of the build used to produce the current prod site is different between the two, which makes this difficult to debug from here.

The problem code differs between dev and prod in main.js, although it seems strange that it would be due to the minification.
dev version (minified) working ok:
```
var map = {
  'A':'a',
  // etc
  'Z':'z',
  "\xb5": "\u03bc",
  "\xc0": "\xe0",
  "\xc1": "\xe1",
  "\xc2": "\xe2",
  // etc
}
```
prod version (unminified) not working ok:
```
var map = {
  'A':'a',
  // etc
  'Z':'z',
  µ: "\u03bc",
  À: "\xe0",
  Á: "\xe1",
  Â: "\xe2",
  // etc
}
```

The problem area is in the [commonmark package](https://github.com/commonmark/commonmark.js/blob/master/lib/normalize-reference.js), which is required by react-markdown. You can see in their [dist/commonmark.js](https://github.com/commonmark/commonmark.js/blob/c8798f34bf2e6c219ad477dfa5f1e52eb7ca57e4/dist/commonmark.js#L2317) file that the map is (basically) the same as in the dev version:
```
var map = {
  'A':'a',
  // etc
  'Z':'z',
  '\xB5':'\u03BC',
  '\xC0':'\xE0',
  '\xC1':'\xE1',
  '\xC2':'\xE2',
  // etc
}
```

That file has [always looked that way](https://github.com/commonmark/commonmark.js/commits/master/lib/normalize-reference.js), so it's not some versioning issue.

So it seems like however the production site was built encoded those escaped keys back into unicode.

**Comment by pjm17971** [comment] 2018-09-19 14:03
@iabw yes, exactly.

**Comment by jonaswitt** [comment] 2019-01-03 11:19
I'd love to see this working in Safari. This is an excellent library and being able to look up examples and API documentation in my main browser (Safari) would be great.

I think commonmark.js is doing the right thing (in terms of compatibility) by escaping all strings in that JS file (both dictionary keys and values). There must be an extra minification step outside of this repo's build process when building the software.es.net site that undoes this. @pjm17971 do you know which tools are used? Maybe they can be configured differently.

**Comment by jdugan1024** [comment] 2019-04-24 02:29
The docs now load for me in Safari as of commit 1f6ab2ec92e56c29bbebd8dfc1949fce5a522dab.

Thanks @jonaswitt for the hint -- it looks like prettier was going in an reformatting the minified JS which apparently caused the problem.  See #387 for PR that addresses this.

@sartaj10 and @pjm17971 How does this look?

**Comment by sartaj10** [comment] 2019-04-24 02:31
@jdugan1024 Works perfectly! Thanks for noticing that

**Comment by jdugan1024** [comment] 2019-04-24 16:27
Since this is fixed, I'm going to close this issue.

**Closed by jdugan1024** 2019-04-24 16:27 UTC
Labels: :octocat: help wanted, :spider: bug
