### ISSUE TITLE
Stock Wind and Weather example failing to work on newer react 

### ISSUE THREAD

**Issue by lquinn2015** [esnet/react-timeseries-charts#156] opened 2017-06-06 14:26 UTC
So I am getting weird error where the time range is invalid/undefined I not really sure how to proceed in fixing these as they have been stomping me. These are the errors console is giving me maybe you'd have insight into this problem. 

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
Warning: Weather: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
Warning: Failed prop type: The prop `timeRange` is marked as required in `ChartContainer`, but its value is `undefined`.
    in ChartContainer (created by Weather)
    in Weather (created by App)
    in div (created by App)
    in App
    in Provider
Error: Invalid timerange passed to ChartContainer

Update: I get this problem even after copying the stock package json file and reinstalling dependences so i thing this bug goes deeper than that.

**Comment by pjm17971** [comment] 2017-06-06 14:30
Yeah, React added that warning recently. There's been a fixed merged into master for it, but I've not had time in the last week or so to make a release containing it. You could point to master and give that a try and see if the problem is fixed.

I'm not really sure why you'd get the timeRange error (except if the range was actually undefined). There needs to be a TimeRange passed to the ChartContainer or the x axis will be undefined.

**Comment by lquinn2015** [comment] 2017-06-06 15:12
Sorry but I am still new to react and Javascript in general what do you mean by point to the master?

So i am just going to type out load so maybe i can track the problem. 
So timeRange is set here
<ChartContainer
                timeRange={this.state.timerange}

Then this.state.timerange was set here
getInitialState() {
    return {
      hover: null,
      highlight: null,
      selection: null,
      timerange: series.range()
    };
  },
I assume that getInitalState() is automatically called once on page load or something.
So then series is defined here

const series = new TimeSeries({
  name: "Gust",
  columns: ["time", "station1", "station2"],
  points
});
Finally points is defined 
const points = [];
_.each(weatherJSON, readings => {
  const time = new Moment(readings.Time).toDate().getTime();
  const reading = readings["WindSpeedGustMPH"];
  if (reading !== "-" && reading !== 0) {
    points.push([
      time,
      reading * 5 + Math.random() * 2.5 - 2.5,
      reading * 3 + Math.random() * 4 - 2
    ]);
  }
});
Do you think its possible that the points array has all null time entries because its not written prefect or something along those lines. The rest of the code makes senses to me its just that function is kinda complicated and hard to understand.

**Comment by pjm17971** [comment] 2017-06-06 19:26
Yes, that's how it works. You could verify that the series has data in it, for example: `series.toString()` should print out the time series. Or `series.size()` should tell you the number of points.

That function is just pulling some data from the JSON file. Perhaps weatherJSON has nothing in it? If it does, then the rest of it is just pushing a couple of versions of that in to the points array, [time, v1, v2] where the actual value doesn't really matter, they are effectively random on top of the underlying data in the JSON file. it's just to make a readable scatter plot.

Do you have a clone of the repo, or are you using the library via npm and are trying to reproduce that example? If so, perhaps the JSON loading isn't working?

**Comment by lquinn2015** [comment] 2017-06-06 20:15
So I am doing this via npm library for some reason the JSON wasn't loading i rewrote the command to fix it but just check the command wasn't broken but rather there was some package wasn't enable that i installed when i was reproducing the command. But alas i still haven't gotten this scatter plot functional i am getting these errors below but I will be working on them tomorrow

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Wind`.
    in Wind (created by App)
    in div (created by App)
    in App
    in Provider  bundle.min.js%20line%2079%20%3E%20eval:36:9
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Wind`.
```

**Comment by pjm17971** [comment] 2017-06-06 20:19
That means a component you are importing isn't being imported as you expected, and is undefined. Check your imports to see if one of them is undefined and then figure out why. Unfortunately React is only telling you that its something used within Wind, but not which one it is. Its also telling you that if this is your own module being imported, the problematic component might not be being exported properly.

**Comment by lquinn2015** [comment] 2017-06-07 14:36
Thank you for the help I got everything up and running for anyone problem with the json loading try this 
`
const weatherJSON = require('json!./weather.json');`

Also get "json-loader": "^0.5.4", should fix any json problem

Feel free to close the question thank you for you time

**Closed** 2017-06-12 22:00 UTC
Labels: question
