### ISSUE TITLE
dep:moment-duration-format issue with webpack

### ISSUE THREAD

**Issue by navtej** [esnet/react-timeseries-charts#88] opened 2016-10-20 17:52 UTC
I am using react-timeseries-charts with react-boilerplate. I run into problem as soon as I import react-timeseries-charts eg `import {  ChartContainer } from 'react-timeseries-charts';`. The error in browser is 

> moment-duration-format.js:202 Uncaught (in promise) TypeError: Cannot read property 'fn' of undefined(…)(anonymous function) 

It appears the issue was fixed upstream (moment-duration-format repo) in dev branch with https://github.com/jsmreese/moment-duration-format/commit/5698eccd2c1e8717e736146b7a6b464b2625508d

Some more info:
https://github.com/jsmreese/moment-duration-format/issues/29
https://github.com/jsmreese/moment-duration-format/issues/34

workaround by using `window.moment = require('moment');` or `var moment = require('moment');` doesn't works either.
Do you think updating `package.json` of `react-timeseries-charts` to pint to git url with #dev branch can solve the issue?

**Comment by pjm17971** [comment] 2016-10-24 14:51
We could do that, not really ideal though.

**Comment by pjm17971** [comment] 2017-02-25 03:40
I'm closing this, because people don't seem to be having an issue. Note that if the react-axis integration ever happens, this dependency will go away.

**Comment by zsherman** [comment] 2017-03-21 05:01
+1 also ran into this issue

**Comment by garetmckinley** [comment] 2017-04-06 19:51
Getting this as well

**Comment by zsherman** [comment] 2017-04-06 20:20
Webpack seems to be one of the defacto tools for handling js and I'm able to reproduce this issue across multiple configurations. As far as I'm concerned this is actually a relatively high priority issue, particularly if we want to encourage adoption and contributions to this excellent lib.

**Comment by pjm17971** [comment] 2017-04-06 22:17
We use this library in multiple projects all of which use webpack. I'm happy to try to fix this, but I'm not currently able to reproduce this.

The proposed solution is actually to get rid of this dependency because of the way it attaches itself into moment, which presumably is creating a dependency ordering issue where sometimes it fails, sometimes its fine. The library also seems barely maintained. The replacement would be to use react-axis which was started in part to solve this. However, I'm lacking the cycles right now to get that work integrated into this library and fix the tail of small issues around doing that.

So that's the longer term plan. If there's a specific suggestion / PR that can help with this, please let me know here.

**Comment by zsherman** [comment] 2017-04-06 22:23
Thanks for the quick response, one idea would just be to use the dev branch from moment-duration-format which has a fix for this issue, but that might be a little hacky. react-axis definitely looks like a good call.

**Comment by navtej** [comment] 2017-04-07 05:20
@zsherman I had tried getting the #dev branch of dep in the time series, it still didnt worked. You check and pull the specific commit f7415efb824b5cd233011bc7601b0035fa7f3423 from https://github.com/navtej/react-timeseries-charts . I tried couple of things to make it work, however eventually i gave up. I am not that well versed with node/js ecosystem. May be some more skilled person can give it another shot.

**Comment by sartaj10** [comment] 2018-05-24 18:33
@navtej @zsherman @garetmckinley
Does this error still exist?

**Comment by navtej** [comment] 2018-05-24 20:09
Not sure, I haven't tried it in a  while.

**Closed** 2018-05-29 23:30 UTC
Labels: :octocat: help wanted, :question: question

**Comment by laszlocph** [comment] 2020-06-17 09:08
Getting `moment.duration is undefined` in the browser.

**Comment by riccardobellini** [comment] 2020-06-29 07:26
I also ran into the same issue, I'm using the react-timeseries-charts version 0.16.1, which seems to depend on moment-duration-format ^1.3.0 that does not include the upstream fix mentioned in the first post.

**Comment by riccardobellini** [comment] 2020-08-05 14:09
I have found a workaround after banging my head against it for a couple of days, didn't share it before because I didn't have time.
Problem lies in the way moment is default-exported via ESM and "required" with CJS syntax in moment-duration format, but without using .default suffix (see [this](https://github.com/babel/babel/issues/2212) note about babel dropping the old default export/import behaviour).
The workaround I found was explicitly using the "add-module-exports" babel plugin, together with the "plugin-transform-modules-commonjs" plugin, and processing moment explicitly with those plugins. The relevant snippet of my webpack configuration is a new rule configured as follows

```javascript
{
  test: /\.(m?js)$/,
  include: /node_modules\/moment\//,
  use: {
    loader: 'babel-loader',
    options: {
      plugins: [
        ["@babel/plugin-transform-modules-commonjs", {
          "allowTopLevelThis": true
        }],
        "add-module-exports"
      ]
    }
  }
}
```

This managed to make things work for me, I don't know if will work for you straight away, just thought someone might be interested in trying a workaround.

**Comment by mathiash98** [comment] 2023-06-30 12:08
Upgrading a very old repo here, I fixed it by adding following to package.json:

```
// NPM
"overrides": {
    "react-timeseries-charts": {
      "moment-duration-format": "^2.3.2"
    }
  },
// Yarn
  "resolutions": {
    "moment-duration-format": "^2.3.2"
  },
```
