### ISSUE TITLE
Zooming Start Issue

### ISSUE THREAD

**Issue by mustafaibrahim989** [esnet/react-timeseries-charts#169] opened 2017-07-19 16:46 UTC
I've a line graph with zoom enabled and every time I'm zooming the graph starts to zoom from the beginning even if I've started from the middle or the right. I checked the updated range object and I noticed that the first item is fixed along the zooming process and only the second item is changing. So What do you think?

**Comment by pjm17971** [comment] 2017-07-19 20:17
From your description I'm not sure, but likely it has to do with constraints on the zoom. For instance if you have specified a min or max time it won't zoom out past that. Can you paste your chart code and/or an animation of the behavior you are seeing?

**Comment by mustafaibrahim989** [comment] 2017-07-20 09:25
Hello @pjm17971, Here's some details:
![untitled](https://user-images.githubusercontent.com/1499047/28410358-b84bc93a-6d3d-11e7-9810-30816b57b2e4.gif)

and here's a sample of timerange sent by onTimeRangeChanged()
[1500541666000,1500542560105]  
[1500541666000,1500542543117]  
[1500541666000,1500542422074]  
[1500541666000,1500542328320]  
[1500541666000,1500542311099]  
[1500541666000,1500542129826]  
[1500541666000,1500542095966]  
[1500541666000,1500542091666]  
[1500541666000,1500542081024]  
[1500541666000,1500542078533]  
[1500541666000,1500542077707]
Also I'm setting the min & max by the time series range min and max

**Comment by pjm17971** [comment] 2017-07-24 14:06
@sartaj10 can you look at this?

**Comment by pjm17971** [comment] 2017-07-24 16:45
@mustafaibrahim989 Can you try to remove the `minTime` and `maxTime` props and see if that fixes the behavior. If they are there it will maintain the begin time as you are seeing. You can also look at the [currency](http://software.es.net/react-timeseries-charts/#/example/currency) example for how it is supposed to behave when there are constraints on the time axis like you have.

**Comment by pjm17971** [comment] 2017-09-01 22:48
I'm not sure we have enough information to address this. I couldn't reproduce so I'm closing for now.

**Closed by pjm17971** 2017-09-01 22:48 UTC
